name: go-mod-tidy-pr
description: Run `go mod tidy` and create PullRequest
author: sue445
inputs: 
  github_token:
    description: GitHub Token
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - --github-token ${{ inputs.github_token }}
